steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/block-management:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/block-management:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'block-management'
      - '--image=gcr.io/$PROJECT_ID/block-management:$COMMIT_SHA'
      - '--region=europe-west2'
      - '--platform=managed'
      - '--no-allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'

images:
  - 'gcr.io/$PROJECT_ID/block-management:$COMMIT_SHA'
